#include "compiler/codegen/CodeGenerator.h"
#include "compiler/optimizer/Optimizer.h"
#include "compiler/semantic/SemanticAnalyzer.h"
#include "compiler/parser/Parser.h"
#include "compiler/lexer/Lexer.h"
#include <iostream>

void testCodeGeneration(const std::string& testName, const std::string& source, bool optimize = false) {
    std::cout << "════════════════════════════════════════\n";
    std::cout << "Test: " << testName << "\n";
    std::cout << "════════════════════════════════════════\n";
    std::cout << "Source:\n" << source << "\n\n";
    
    try {
        // Lex
        Lexer lexer(source);
        auto tokens = lexer.getAllTokens();
        
        // Parse
        Parser parser(tokens);
        auto program = parser.parse();
        
        // Semantic analysis
        SemanticAnalyzer analyzer(program);
        analyzer.analyze();
        
        if (analyzer.hasErrors()) {
            std::cout << "❌ Semantic errors found:\n";
            for (const auto& error : analyzer.getErrors()) {
                std::cout << "  • " << error.what() << "\n";
            }
            return;
        }
        
        // Optimize (if requested)
        if (optimize) {
            Optimizer optimizer;
            optimizer.optimize(program);
            std::cout << "Optimization: " << optimizer.getOptimizationCount() 
                      << " optimization(s) applied\n\n";
        }
        
        // Generate bytecode
        CodeGenerator codegen;
        BytecodeProgram bytecode = codegen.generate(program);
        
        std::cout << "Generated Bytecode:\n";
        bytecode.print();
        
        std::cout << "✅ Code generation successful!\n";
        
    } catch (const std::exception& e) {
        std::cout << "❌ Error: " << e.what() << "\n";
    }
    
    std::cout << "\n";
}

int main() {
    std::cout << "╔════════════════════════════════════════════╗\n";
    std::cout << "║  Educational Compiler - CodeGen Tests     ║\n";
    std::cout << "╚════════════════════════════════════════════╝\n\n";
    
    // Test 1: Simple variable declaration
    testCodeGeneration(
        "Simple Declaration",
        "let x = 42;"
    );
    
    // Test 2: Arithmetic expression
    testCodeGeneration(
        "Arithmetic Expression",
        "let y = 10 + 20;"
    );
    
    // Test 3: Complex expression (with optimization)
    testCodeGeneration(
        "Complex Expression (Optimized)",
        "let z = 2 + 3 * 4;",
        true
    );
    
    // Test 4: Variable usage
    testCodeGeneration(
        "Variable Usage",
        "let a = 5;\n"
        "let b = a + 10;"
    );
    
    // Test 5: Print statement
    testCodeGeneration(
        "Print Statement",
        "let x = 42;\n"
        "print x;"
    );
    
    // Test 6: Multiple operations
    testCodeGeneration(
        "Multiple Operations",
        "let a = 10;\n"
        "let b = 20;\n"
        "let sum = a + b;\n"
        "print sum;"
    );
    
    // Test 7: Nested expressions
    testCodeGeneration(
        "Nested Expressions",
        "let result = (10 + 5) * (8 - 3);"
    );
    
    // Test 8: Optimized nested (should be much shorter)
    testCodeGeneration(
        "Nested Expressions (Optimized)",
        "let result = (10 + 5) * (8 - 3);",
        true
    );
    
    // Test 9: Comparison operators
    testCodeGeneration(
        "Comparison Operators",
        "let flag = 10 > 5;\n"
        "let check = 3 == 3;"
    );
    
    // Test 10: All arithmetic operators
    testCodeGeneration(
        "All Arithmetic Operators",
        "let a = 10 + 3;\n"
        "let b = 10 - 3;\n"
        "let c = 10 * 3;\n"
        "let d = 10 / 3;\n"
        "let e = 10 % 3;"
    );
    
    // Test 11: Print with expression
    testCodeGeneration(
        "Print with Expression",
        "print 2 + 3 * 4;"
    );
    
    // Test 12: Optimized constant folding comparison
    std::cout << "════════════════════════════════════════\n";
    std::cout << "Optimization Impact Comparison\n";
    std::cout << "════════════════════════════════════════\n\n";
    
    std::cout << "WITHOUT Optimization:\n";
    testCodeGeneration(
        "",
        "let x = 2 + 3 * 4;",
        false
    );
    
    std::cout << "WITH Optimization:\n";
    testCodeGeneration(
        "",
        "let x = 2 + 3 * 4;",
        true
    );
    
    std::cout << "╔════════════════════════════════════════════╗\n";
    std::cout << "║          All Tests Completed!              ║\n";
    std::cout << "╚════════════════════════════════════════════╝\n";
    
    return 0;
}
